//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Siemens' Register Assistant V2025.1 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : design
// Unit            : design_pkg_uvm
// File            : design_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : meita
// Creation Date   : 2/6/26 10:17 AM
//----------------------------------------------------------------------
// Title           : design
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// design_pkg_uvm
//----------------------------------------------------------------------
package design_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"


   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: COUNT_IN_reg
   // 
   // Total accepted input packets
   //--------------------------------------------------------------------

   class COUNT_IN_reg extends uvm_reg;
      `uvm_object_utils(COUNT_IN_reg)

      uvm_reg_field COUNT_IN_reg; 


      // Function: new
      // 
      function new(string name = "COUNT_IN_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         COUNT_IN_reg = uvm_reg_field::type_id::create("COUNT_IN_reg");

         COUNT_IN_reg.configure(this, 32, 0, "RO", 0, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: COUNT_OUT_reg
   // 
   // Total output packets
   //--------------------------------------------------------------------

   class COUNT_OUT_reg extends uvm_reg;
      `uvm_object_utils(COUNT_OUT_reg)

      uvm_reg_field COUNT_OUT_reg; 


      // Function: new
      // 
      function new(string name = "COUNT_OUT_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         COUNT_OUT_reg = uvm_reg_field::type_id::create("COUNT_OUT_reg");

         COUNT_OUT_reg.configure(this, 32, 0, "RO", 0, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: CTRL_reg
   // 
   // Enable CPM operation
   //--------------------------------------------------------------------

   class CTRL_reg extends uvm_reg;
      `uvm_object_utils(CTRL_reg)

      uvm_reg_field RESERVED; 
      rand uvm_reg_field SOFT_RST; 
      rand uvm_reg_field ENABLE; 


      // Function: new
      // 
      function new(string name = "CTRL_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         RESERVED = uvm_reg_field::type_id::create("RESERVED");
         SOFT_RST = uvm_reg_field::type_id::create("SOFT_RST");
         ENABLE = uvm_reg_field::type_id::create("ENABLE");

         RESERVED.configure(this, 30, 2, "RO", 0, 30'b000000000000000000000000000000, 1, 0, 0);
         SOFT_RST.configure(this, 1, 1, "RW", 0, 1'b0, 1, 1, 0);
         ENABLE.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DROPPED_COUNT_reg
   // 
   // Total dropped packets
   //--------------------------------------------------------------------

   class DROPPED_COUNT_reg extends uvm_reg;
      `uvm_object_utils(DROPPED_COUNT_reg)

      uvm_reg_field DROPPED_COUNT_reg; 


      // Function: new
      // 
      function new(string name = "DROPPED_COUNT_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         DROPPED_COUNT_reg = uvm_reg_field::type_id::create("DROPPED_COUNT_reg");

         DROPPED_COUNT_reg.configure(this, 32, 0, "RO", 0, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DROP_CFG_reg
   // 
   // Enable drop mechanism
   //--------------------------------------------------------------------

   class DROP_CFG_reg extends uvm_reg;
      `uvm_object_utils(DROP_CFG_reg)

      uvm_reg_field RESERVED1; 
      rand uvm_reg_field DROP_OPCODE; 
      uvm_reg_field RESERVED0; 
      rand uvm_reg_field DROP_EN; 


      // Function: new
      // 
      function new(string name = "DROP_CFG_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         RESERVED1 = uvm_reg_field::type_id::create("RESERVED1");
         DROP_OPCODE = uvm_reg_field::type_id::create("DROP_OPCODE");
         RESERVED0 = uvm_reg_field::type_id::create("RESERVED0");
         DROP_EN = uvm_reg_field::type_id::create("DROP_EN");

         RESERVED1.configure(this, 24, 8, "RO", 0, 24'h000000, 1, 0, 1);
         DROP_OPCODE.configure(this, 4, 4, "RW", 0, 4'h0, 1, 1, 0);
         RESERVED0.configure(this, 3, 1, "RO", 0, 3'b000, 1, 0, 0);
         DROP_EN.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: MODE_reg
   // 
   // Operation mode: 0=PASS 1=XOR 2=ADD 3=ROT
   //--------------------------------------------------------------------

   class MODE_reg extends uvm_reg;
      `uvm_object_utils(MODE_reg)

      uvm_reg_field RESERVED; 
      rand uvm_reg_field MODE_reg; 


      // Function: new
      // 
      function new(string name = "MODE_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         RESERVED = uvm_reg_field::type_id::create("RESERVED");
         MODE_reg = uvm_reg_field::type_id::create("MODE_reg");

         RESERVED.configure(this, 30, 2, "RO", 0, 30'b000000000000000000000000000000, 1, 0, 0);
         MODE_reg.configure(this, 2, 0, "RW", 0, 2'b00, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: PARAMS_reg
   // 
   // XOR mask
   //--------------------------------------------------------------------

   class PARAMS_reg extends uvm_reg;
      `uvm_object_utils(PARAMS_reg)

      rand uvm_reg_field ADD_CONST; 
      rand uvm_reg_field MASK; 


      // Function: new
      // 
      function new(string name = "PARAMS_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         ADD_CONST = uvm_reg_field::type_id::create("ADD_CONST");
         MASK = uvm_reg_field::type_id::create("MASK");

         ADD_CONST.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 1, 1);
         MASK.configure(this, 16, 0, "RW", 0, 16'h0000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: STATUS_reg
   // 
   // Indicates pending transactions in pipeline
   //--------------------------------------------------------------------

   class STATUS_reg extends uvm_reg;
      `uvm_object_utils(STATUS_reg)

      uvm_reg_field RESERVED; 
      uvm_reg_field BUSY; 


      // Function: new
      // 
      function new(string name = "STATUS_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         RESERVED = uvm_reg_field::type_id::create("RESERVED");
         BUSY = uvm_reg_field::type_id::create("BUSY");

         RESERVED.configure(this, 31, 1, "RO", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         BUSY.configure(this, 1, 0, "RO", 0, 1'b0, 1, 0, 0);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: cpm_reg_map
   // 
   //--------------------------------------------------------------------

   class cpm_reg_map extends uvm_reg_block;
      `uvm_object_utils(cpm_reg_map)

      rand CTRL_reg CTRL; // Enable CPM operation
      rand MODE_reg MODE; // Operation mode: 0=PASS 1=XOR 2=ADD 3=ROT
      rand PARAMS_reg PARAMS; // XOR mask
      rand DROP_CFG_reg DROP_CFG; // Enable drop mechanism
      rand STATUS_reg STATUS; // Indicates pending transactions in pipeline
      rand COUNT_IN_reg COUNT_IN; // Total accepted input packets
      rand COUNT_OUT_reg COUNT_OUT; // Total output packets
      rand DROPPED_COUNT_reg DROPPED_COUNT; // Total dropped packets

      uvm_reg_map cpm_reg_map_map; 


      // Function: new
      // 
      function new(string name = "cpm_reg_map");
         super.new(name, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         CTRL = CTRL_reg::type_id::create("CTRL");
         CTRL.configure(this);
         CTRL.build();

         MODE = MODE_reg::type_id::create("MODE");
         MODE.configure(this);
         MODE.build();

         PARAMS = PARAMS_reg::type_id::create("PARAMS");
         PARAMS.configure(this);
         PARAMS.build();

         DROP_CFG = DROP_CFG_reg::type_id::create("DROP_CFG");
         DROP_CFG.configure(this);
         DROP_CFG.build();

         STATUS = STATUS_reg::type_id::create("STATUS");
         STATUS.configure(this);
         STATUS.build();

         COUNT_IN = COUNT_IN_reg::type_id::create("COUNT_IN");
         COUNT_IN.configure(this);
         COUNT_IN.build();

         COUNT_OUT = COUNT_OUT_reg::type_id::create("COUNT_OUT");
         COUNT_OUT.configure(this);
         COUNT_OUT.build();

         DROPPED_COUNT = DROPPED_COUNT_reg::type_id::create("DROPPED_COUNT");
         DROPPED_COUNT.configure(this);
         DROPPED_COUNT.build();

         cpm_reg_map_map = create_map("cpm_reg_map_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = cpm_reg_map_map;

         cpm_reg_map_map.add_reg(CTRL, 'h0, "RW");
         cpm_reg_map_map.add_reg(MODE, 'h4, "RW");
         cpm_reg_map_map.add_reg(PARAMS, 'h8, "RW");
         cpm_reg_map_map.add_reg(DROP_CFG, 'hc, "RW");
         cpm_reg_map_map.add_reg(STATUS, 'h10, "RO");
         cpm_reg_map_map.add_reg(COUNT_IN, 'h14, "RO");
         cpm_reg_map_map.add_reg(COUNT_OUT, 'h18, "RO");
         cpm_reg_map_map.add_reg(DROPPED_COUNT, 'h1c, "RO");

         lock_model();
      endfunction
   endclass


endpackage
